
    
build: off

clone_folder: c:\gopath\src\github.com\alibabacloud-go\rpc-client

environment:
  GOPATH: c:\gopath
  matrix:
    - go: 1.11.x
    - go: 1.12.x

platform:
  - x64

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - export GO111MODULE=on
  - go mod tidy

test_script:
  - go vet ./utils
  - go vet ./service/...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./utils/... ./service/...

after_test:
  - bash <(curl -s https://codecov.io/bash)